// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyswblkrrbsnunfarudj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5c3dibGtycmJzbnVuZmFydWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTA1ODUsImV4cCI6MjA1NDY2NjU4NX0.fFsNHrRvBzLcksLRKBCrxopZBlh8u8IcZH3zv2DVqZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);